// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0ivPiQe0yToOapHpYkuiboMoZGzsYFMw',
    appId: '1:892880484739:web:56a7952c0fceb3493c1eb6',
    messagingSenderId: '892880484739',
    projectId: 'books-management-13c74',
    authDomain: 'books-management-13c74.firebaseapp.com',
    storageBucket: 'books-management-13c74.appspot.com',
    measurementId: 'G-L6YG4NL3N7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9wr8LWFG4BTr6zW2LKiWI0J_3Tele_b0',
    appId: '1:892880484739:android:021554a3329802353c1eb6',
    messagingSenderId: '892880484739',
    projectId: 'books-management-13c74',
    storageBucket: 'books-management-13c74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4v0kuJZ4dGislQz8frvzkAoKQ1vhuMyU',
    appId: '1:892880484739:ios:0f0da9493715bdf13c1eb6',
    messagingSenderId: '892880484739',
    projectId: 'books-management-13c74',
    storageBucket: 'books-management-13c74.appspot.com',
    iosClientId: '892880484739-8k6le7p305iemkpashdn54p1t4dge8em.apps.googleusercontent.com',
    iosBundleId: 'com.example.quanLyThuVien',
  );
}
